package uber.shared;

public enum TipoMensaje {

    SOLICITAR_VIAJE,
    PROGRAMAR_VIAJE,
    CONSULTAR_VIAJES,
    FINALIZAR_VIAJE,

    RESPUESTA_VIAJE,
    RESPUESTA_PROGRAMAR,
    RESPUESTA_CONSULTA,
    RESPUESTA_FINALIZAR,

    ACK,
    ERROR,

    HEARTBEAT,
    HEARTBEAT_ACK,

    ELECTION,
    ELECTION_OK,
    COORDINATOR,
    REPLICAR_ESTADO,

    CONSULTAR_METRICAS,
    RESPUESTA_METRICAS
}